
name: ğŸ•ä¸œxlcå¯»æ¬¢

on:
    workflow_dispatch:
    schedule:
        - cron: "5 */3 * * *"
    watch:
        types: [started]
    repository_dispatch:
        types: ğŸ•ä¸œxlcå¯»æ¬¢

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: npm install
              run: |
                  npm install
            - name: 'è¿è¡Œ ã€ğŸ•ä¸œå†œåœºã€‘'
              run: |
               node Club.js
              env:
               JD_COOKIE: ${{ secrets.JD_COOKIE }}
               SYNCURL: fully/master/jd_ddnc.js
               XLC: ${{ secrets.XLC }}
               GITHUB: ${{ secrets.GITHUB }}
               EFORK: ${{ secrets.EFORK }}
               
            - uses: actions/checkout@v1
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: npm install
              run: |
                  npm install
            - name: 'è¿è¡Œ ã€ğŸ•ç§Dã€‘'
              run: |
               node Club.js
              env:
               JD_COOKIE: ${{ secrets.JD_COOKIE }}
               SYNCURL: fully/master/jd_zd.js
               XLC: ${{ secrets.XLC }}
               GITHUB: ${{ secrets.GITHUB }}
               EFORK: ${{ secrets.EFORK }}
            
            
            - uses: actions/checkout@v1
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: npm install
              run: |
                  npm install
            - name: 'è¿è¡Œ ã€ğŸ•èŒã€‘'
              run: |
                node Club.js
              env:
               JD_COOKIE: ${{ secrets.JD_COOKIE }}
               SYNCURL: fully/master/jd_mc.js
               XLC: ${{ secrets.XLC }}
               GITHUB: ${{ secrets.GITHUB }}
               EFORK: ${{ secrets.EFORK }}
            
            
            - uses: actions/checkout@v1
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: npm install
              run: |
                  npm install
            - name: 'è¿è¡Œ ã€ğŸ•Då·¥ã€‘'
              run: |
                node Club.js
              env:
                 JD_COOKIE: ${{ secrets.JD_COOKIE }}
                 SYNCURL: fully/master/jd_ddgc.js
                 XLC: ${{ secrets.XLC }}
                 GITHUB: ${{ secrets.GITHUB }}
                 EFORK: ${{ secrets.EFORK }}
  
            - uses: actions/checkout@v1
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: npm install
              run: |
                  npm install
            - name: 'è¿è¡Œ ã€ğŸ•Xå·¥ã€‘'
              run: |
                node Club.js
              env:
                JD_COOKIE: ${{ secrets.JD_COOKIE }}
                SYNCURL: fully/master/jx_gc.js
                XLC: ${{ secrets.XLC }}
                GITHUB: ${{ secrets.GITHUB }}
                EFORK: ${{ secrets.EFORK }}
  
           
            - uses: actions/checkout@v1
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: npm install
              run: |
                  npm install
            - name: 'è¿è¡Œ ã€ğŸ•ä¸œå¿é‡‘æ´ªåŒ…ã€‘'
              run: |
               node Club.js
              env:
                 JD_COOKIE: ${{ secrets.JD_COOKIE }}
                 SYNCURL: fully/master/jdhb.js
                 XLC: ${{ secrets.XLC }}
                 GITHUB: ${{ secrets.GITHUB }}
                 EFORK: ${{ secrets.EFORK }}
  
            
            - uses: actions/checkout@v1
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: npm install
              run: |
                  npm install
            - name: 'è¿è¡Œ ã€ğŸ•ä¸œå–å…³ã€‘'
              run: |
               node Club.js
              env:
                JD_COOKIE: ${{ secrets.JD_COOKIE }}
                SYNCURL: fully/master/jd_unsubscribe.js
                XLC: ${{ secrets.XLC }}
                GITHUB: ${{ secrets.GITHUB }}
                EFORK: ${{ secrets.EFORK }}
  
            
            - uses: actions/checkout@v1
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: npm install
              run: |
                  npm install
            - name: 'è¿è¡Œ ã€ğŸ•ä¸œTRYã€‘'
              run: |
               node Club.js
              env:
                JD_COOKIE: ${{ secrets.JD_COOKIE }}
                SYNCURL: fully/master/try.js
                TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
                TG_USER_ID: ${{ secrets.TG_USER_ID }}
                XLC: ${{ secrets.XLC }}
                GITHUB: ${{ secrets.GITHUB }}  
                EFORK: ${{ secrets.EFORK }}
  
            
 
