name: ğŸ•X

on:
  workflow_dispatch:
  schedule:
    - cron: '36 * * * *'
  watch:
  repository_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
            node-version: 12.x
      - name: npm install
        run: |
            npm install
      - name: 'è¿è¡Œ ã€ğŸ•+suã€‘'
        run: |
            node Club.js
        env:
            JD_COOKIE: ${{ secrets.JD_COOKIE }}
            SYNCURL: fully/master/DG/j0d_sp0eed.js
            XLC: ${{ secrets.XLC }}
            GITHUB: ${{ secrets.GITHUB }}
            EFORK: ${{ secrets.EFORK }}   
            
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
            node-version: 12.x
      - name: npm install
        run: |
            npm install
      - name: 'è¿è¡Œ ã€ğŸ•æ½®Sã€‘'
        run: |
            node Club.js
        env:
            JD_COOKIE: ${{ secrets.JD_COOKIE }}
            SYNCURL: fully/master/DG/DJSM.js
            XLC: ${{ secrets.XLC }}
            GITHUB: ${{ secrets.GITHUB }}
            EFORK: ${{ secrets.EFORK }}
            
            
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
            node-version: 12.x
      - name: npm install
        run: |
            npm install
      - name: 'è¿è¡Œ ã€ğŸ•ğŸ–ã€‘'
        run: |
           node Club.js
        env:
            JD_COOKIE: ${{ secrets.JD_COOKIE }}
            SYNCURL: fully/master/DG/pi0gPe0t0.js
            XLC: ${{ secrets.XLC }}
            GITHUB: ${{ secrets.GITHUB }}
            EFORK: ${{ secrets.EFORK }}
           
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
            node-version: 12.x
      - name: npm install
        run: |
            npm install
      - name: 'è¿è¡Œ ã€ğŸ•æ‘‡æ ‘ã€‘'
        run: |
            node Club.js
        env:
            JD_COOKIE: ${{ secrets.JD_COOKIE }}
            SYNCURL: fully/master/DG/j1d_mon0eyT0ree.js
            XLC: ${{ secrets.XLC }}
            GITHUB: ${{ secrets.GITHUB }}
            EFORK: ${{ secrets.EFORK }}
    
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: justnew138/you
          ref: 'main'
          token: ${{ secrets.PAT }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
      - name: npm install
        run: |
          npm install
      - name: 'ğŸ•Fd'
        run: |
          node cfd.js
        env:
              JD_COOKIE: ${{ secrets.JD_COOKIE }}
              JXNCTOKENS: ${{ secrets.JXNCTOKENS }}
              XLC: ${{ secrets.XLC }}
              GITHUB: ${{ secrets.GITHUB }}
              EFORK: ${{ secrets.EFORK }}

      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
            node-version: 12.x
      - name: npm install
        run: |
            npm install
      - name: 'è¿è¡Œ ã€ğŸ•ç§Dã€‘'
        run: |
               node Club.js
        env:
               JD_COOKIE: ${{ secrets.JD_COOKIE }}
               SYNCURL: fully/master/jd_zd.js
               XLC: ${{ secrets.XLC }}
               GITHUB: ${{ secrets.GITHUB }}
               EFORK: ${{ secrets.EFORK }}
            
            
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
            node-version: 12.x
      - name: npm install
        run: |
            npm install
      - name: 'è¿è¡Œ ã€ğŸ•é¹…ã€‘'
        run: |
                node Club.js
        env:
               JD_COOKIE: ${{ secrets.JD_COOKIE }}
               SYNCURL: fully/master/DG/da0ily_e00gg.js
               XLC: ${{ secrets.XLC }}
               GITHUB: ${{ secrets.GITHUB }}
               EFORK: ${{ secrets.EFORK }}
            
            
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
            node-version: 12.x
      - name: npm install
        run: |
            npm install
      - name: 'è¿è¡Œ ã€ğŸ•Då·¥ã€‘'
        run: |
          node Club.js
        env:
           JD_COOKIE: ${{ secrets.JD_COOKIE }}
           SYNCURL: fully/master/jd_ddgc.js
           XLC: ${{ secrets.XLC }}
           GITHUB: ${{ secrets.GITHUB }}
           EFORK: ${{ secrets.EFORK }}
  
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
            node-version: 12.x
      - name: npm install
        run: |
            npm install
      - name: 'è¿è¡Œ ã€ğŸ•Xå·¥ã€‘'
        run: |
             node Club.js
        env:
            JD_COOKIE: ${{ secrets.JD_COOKIE }}
            SYNCURL: fully/master/jx_gc.js
            XLC: ${{ secrets.XLC }}
            GITHUB: ${{ secrets.GITHUB }}
            EFORK: ${{ secrets.EFORK }}
